services:
  db:
    image: mysql:latest
    container_name: CoutureDB
    environment:
      MYSQL_ROOT_PASSWORD: 12345  # Contraseña root
      MYSQL_DATABASE: Couture
      MYSQL_USER: rodrigo
      MYSQL_PASSWORD: 12345
    ports:
      - "3305:3306"  # Exponer el puerto de MySQL para acceso desde la red local
    volumes:
      - db_data:/var/lib/mysql  # Volumen para persistencia de datos
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_couture
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 12345  # Contraseña root para conectar phpMyAdmin
    ports:
      - "8082:80"  # phpMyAdmin estará accesible en el puerto 8080
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db_data: